# Generated by Django 2.0.2 on 2018-06-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegrambotcommand',
            name='user',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='last_command_date',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='last_command',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='TelegramBotCommand',
        ),
    ]
